<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5Dleio\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5Dleio/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ5Dleio.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ5Dleio\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQ5Dleio\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Q5Dleio',
    'container.build_id' => '1ac03311',
    'container.build_time' => 1556811594,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5Dleio');
